GET http://localhost:8080/locations

###

GET http://localhost:8080/locations/5

###

DELETE http://localhost:8080/locations/5

###

POST http://localhost:8080/locations/
Content-type: application/json

{ "id": 7, "latidude": 60, "longitude": 27 }